### ISSUE TITLE
Error: Could not open directory /home/USER/.local/share/applications

### ISSUE THREAD

**Issue by diogogomes** [godlikemouse/xfce4-finder#4]
I've installed the finder with Pamac in Manjaro and when I try to run I get this error:

`Error: Could not open directory /home/USER/.local/share/applications`

The finder not start the path in system root `/` but in user folder `/home/USER`

**Comment by godlikemouse** [comment]
Hi @diogo-gomes,

The default search paths for this application are:

"/usr/share/applications",
"/usr/share/applications/kde4",
HOME_DIRECTORY + "/.local/share/applications"

Where are your "share/applications" folders located?  Perhaps, I need to add some for of dynamic lookup to make this system independent.  Either that or perhaps a settings configuration.

**Comment by diogogomes** [comment]
Sorry but I don't use Manjaro any more. Now I'm using Xubuntu.

You can close this issue if you want (I can't test xfce4-finder)

**Comment by godlikemouse** [comment]
No problem, sorry for the late reply.  Just now got around to it.  Thanks.
